# This is a basic workflow to help you get started with Actions

name: LintAndTest

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
#  lint:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
#    - name: Rubocop Linter Action
#      uses: andrewmcodes/rubocop-linter-action@v3.1.0
#    env:
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Runs a set of commands using the runners shell

  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-    
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Build and test with Rake
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libsqlite3-dev
          sudo apt-get install libpq-dev
          gem install bundler:1.16.6
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails test
